### ISSUE TITLE
Can't configure some settings.

### ISSUE THREAD

**Issue by willcharlton** [tadpol/MrMurano#28]
We're seeing an issue with configuring `mr`. Here are some interesting stacktraces of trying to set up an environment 

### System info
```
user@Latitude-E5440:~$ uname -a
Linux Latitude-E5440 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
user@Latitude-E5440:~$ mr -v
mr 1.9.0
```

```
user@Latitude-E5440:~$ gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /home/user/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /home/user/.rbenv/versions/2.3.1/bin/ruby
  - EXECUTABLE DIRECTORY: /home/user/.rbenv/versions/2.3.1/bin
  - SPEC CACHE DIRECTORY: /home/user/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/user/.rbenv/versions/2.3.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0
     - /home/user/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/user/.rbenv/versions/2.3.1/bin
     - /home/user/.rbenv/libexec
     - /home/user/.rbenv/plugins/ruby-build/bin
     - /home/user/.rbenv/plugins/ruby-build/bin
     - /home/user/.rbenv/shims
     - /home/user/.rbenv/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
```

### init
```
user@Latitude-E5440:~$ mr init --trace
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/MrMurano-1.9.0/lib/MrMurano/commands/init.rb:15:in `block (2 levels) in <top (required)>': undefined method `+' for nil:NilClass (NoMethodError)
    from /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
    from /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
    from /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
    from /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
    from /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'
```

### user.name
```
user@Latitude-E5440:~$ mr config user.name user+dqa-gwe@exosite.com --trace
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/MrMurano-1.9.0/lib/MrMurano/Config.rb:228:in `set': Unknown scope (RuntimeError)
    from /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/MrMurano-1.9.0/lib/MrMurano/commands/config.rb:61:in `block (2 levels) in <top (required)>'
    from /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
    from /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
    from /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
    from /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
    from /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'
```
### net.host
```
user@Latitude-E5440:~$ mr config net.host bizapi-staging.hosted.exosite.io --trace
/home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/MrMurano-1.9.0/lib/MrMurano/Config.rb:228:in `set': Unknown scope (RuntimeError)
    from /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/MrMurano-1.9.0/lib/MrMurano/commands/config.rb:61:in `block (2 levels) in <top (required)>'
    from /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
    from /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
    from /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
    from /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
    from /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'
```

Let me know if there is more info you need.

Thanks.

**Comment by tadpol** [comment]
Might be related to #25

**Comment by tadpol** [comment]
Have them run `mr config --dump`

**Comment by tadpol** [comment]
also. MrMurano has only been tested with Ruby 2.0 and 2.2  That might be part of this.

**Comment by tadpol** [comment]
Also see #29

**Comment by prakash2810** [comment]
I have not yet tried to lower the `Ruby` version (< 2.3)

**Comment by tadpol** [comment]
It is trying to write to the project directory, but it looks like it isn't in one.  (config location.base is missing)

Try making a directory, changing into it, and running `mr config product.id test1234` again.  I think that should work.

**Comment by prakash2810** [comment]
@tadpol - It worked perfectly, Thanks!

**Comment by tadpol** [comment]
Sounds like this is good. closing it then.
