### ISSUE TITLE
tsdb --aggregate option doesn't return expected results 

### ISSUE THREAD

**Issue by ryankucera** [tadpol/MrMurano#42]
I'm unable to get MrMurano to return aggregated or downsampled aggregated values from a tsdb query. Below is the output from three commands, the first showing the un-aggregated data, the second is an attempt to aggregate, which fails with an error, and the third attempts to downsample and aggregate, which returns null(?) values.

```
MacBook-Pro:scout-tsdb-test ryankucera$ mr tsdb query temperature @sn=E7000021 --limit=5
+---------------------------+-------------+
| time                      | temperature |
+---------------------------+-------------+
| 2016-12-19T14:04:12+00:00 | 28.1        |
| 2016-12-19T14:03:12+00:00 | 28.2        |
| 2016-12-19T14:02:13+00:00 | 28.2        |
| 2016-12-19T14:01:12+00:00 | 28.2        |
| 2016-12-19T14:00:12+00:00 | 28.2        |
+---------------------------+-------------+
MacBook-Pro:scout-tsdb-test ryankucera$ mr tsdb query temperature @sn=E7000021 --limit=5 --aggregate=avg
error: undefined method `each' for nil:NilClass. Use --trace to view backtrace
MacBook-Pro:scout-tsdb-test ryankucera$ mr tsdb query temperature @sn=E7000021 --limit=5 --aggregate=avg --sampling_size=60s
+---------------------------+-------------+
| time                      | temperature |
+---------------------------+-------------+
| 2016-12-19T14:04:00+00:00 |             |
| 2016-12-19T14:03:00+00:00 |             |
| 2016-12-19T14:02:00+00:00 |             |
| 2016-12-19T14:01:00+00:00 |             |
| 2016-12-19T14:00:00+00:00 |             |
+---------------------------+-------------+
```

**Comment by ryankucera** [comment]
Here's the --trace output from the 2nd command above:

```
MacBook-Pro:scout-tsdb-test ryankucera$ mr tsdb query temperature @sn=E7000021 --limit=5 --aggregate=avg --trace
/Library/Ruby/Gems/2.0.0/gems/terminal-table-1.4.5/lib/terminal-table/row.rb:19:in `initialize': undefined method `each' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.4.5/lib/terminal-table/table.rb:100:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.4.5/lib/terminal-table/table.rb:100:in `headings='
	from /Library/Ruby/Gems/2.0.0/gems/terminal-table-1.4.5/lib/terminal-table/table.rb:14:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.11.1/lib/MrMurano/verbosing.rb:57:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.11.1/lib/MrMurano/verbosing.rb:57:in `tabularize'
	from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.11.1/lib/MrMurano/commands/tsdb.rb:187:in `block (3 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.11.1/lib/MrMurano/verbosing.rb:75:in `outf'
	from /Library/Ruby/Gems/2.0.0/gems/MrMurano-1.11.1/lib/MrMurano/commands/tsdb.rb:186:in `block (2 levels) in <top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'
```

**Comment by tadpol** [comment]
yeah, the table format doesn't work with TSDB aggregation yet.  You'll need to add `-c outformat=json` and use [jq](https://stedolan.github.io/jq/) or similar to parse the output.

**Comment by tadpol** [comment]
ok. Next release will support this correctly.
